<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-89PT9N6I" ignored="0" name="Test" tests="2" failures="1" timestamp="2021-05-26T20:13:37 IST" time="67.971" errors="0">
  <testcase name="testCreateIncident" time="18.446" classname="com.servicenow.tests.CreateIncidentTest"/>
  <testcase name="testCreateIncident" time="13.38" classname="com.servicenow.tests.CreateIncidentTest">
    <failure type="java.lang.AssertionError" message="expected [The following mandatory fields are not filled in: Short description] but found [The following mandatory fields are not filled in: Short description, Caller]">
      <![CDATA[java.lang.AssertionError: expected [The following mandatory fields are not filled in: Short description] but found [The following mandatory fields are not filled in: Short description, Caller]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.servicenow.pages.CreateIncidentPage.verifyErrorMessage(CreateIncidentPage.java:45)
at com.servicenow.tests.CreateIncidentTest.testCreateIncident(CreateIncidentTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testCreateIncident -->
</testsuite> <!-- Test -->
